commandes/urls.py
from django.urls import path
from commandes import views


app_name = "commande"

urlpatterns = [
    path("checkout/", views.checkout, name="checkout"),
    path("payer/<int:commande_id>/", views.lancer_paiement, name="lancer_paiement"),
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from django.contrib import admin
from django.urls import path
from ecommerce.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('panier/', include('panier.urls')),
    path('commandes/', include('commandes.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

panier/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/<int:produit_id>/', views.add_to_cart, name='add_to_cart'),
     path('increase/<int:ligne_id>/', views.increase_quantity, name='increase'),
    path('decrease/<int:ligne_id>/', views.decrease_quantity, name='decrease'),
    path('remove/<int:ligne_id>/', views.remove_item, name='remove'),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path('', views.product_list, name='list_products'),
    path('<int:pk>/', views.product_detail, name='detail'),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<str:token>/', views.activate_user, name='activate'),
]

panier/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Produit

class Panier(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_modification = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Panier {self.id} - {self.user}"
    
    def total_items_count(self):
        return self.lignepanier_set.count()
    
    # Nombre des produits dans le panier
    def total_items(self):
        return sum(ligne.quantite for ligne in self.lignepanier_set.all())

    # Montant total dans le panier
    def total_price(self):
        return sum(ligne.total() for ligne in self.lignepanier_set.all())

class LignePanier(models.Model):
    panier = models.ForeignKey(Panier, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantite = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ('panier', 'produit')


    def __str__(self):
        return f"{self.produit.nom} x {self.quantite}"
    
    def total(self):
        return self.quantite * self.produit.prix

panier/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from products.models import Produit
from .models import Panier, LignePanier

# Afficher le panier
@login_required(login_url='login')
def cart_view(request):
    panier, created = Panier.objects.get_or_create(user=request.user)
    return render(request, 'panier/cart.html', {
        'panier': panier
    })


# Ajouter au panier
@login_required(login_url='login')
def add_to_cart(request, produit_id):
    produit = get_object_or_404(Produit, id=produit_id)

    panier, _ = Panier.objects.get_or_create(user=request.user)

    ligne, created = LignePanier.objects.get_or_create(
        panier=panier,
        produit=produit
    )

    if not created:
        ligne.quantite += 1
    ligne.save()

    return JsonResponse({
        "total_items": panier.total_items()
    })


# Diminuer quantité 
@login_required(login_url='login')
def decrease_quantity(request, ligne_id):
    ligne = get_object_or_404(
        LignePanier,
        id=ligne_id,
        panier__user=request.user
    )

    ligne.quantite -= 1
    if ligne.quantite <= 0:
        ligne.delete()
    else:
        ligne.save()

    return redirect('cart')


# Augmenter quantité
@login_required(login_url='login')
def increase_quantity(request, ligne_id):
    ligne = get_object_or_404(
        LignePanier,
        id=ligne_id,
        panier__user=request.user
    )

    ligne.quantite += 1
    ligne.save()
    return redirect('cart')


# Supprimer un produit du panier
@login_required(login_url='login')
def remove_item(request, ligne_id):
    ligne = get_object_or_404(
        LignePanier,
        id=ligne_id,
        panier__user=request.user
    )
    ligne.delete()
    return redirect('cart')

panier/templates/panier/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}Mon panier | Gstyle{% endblock %}

{% block content %}

<!-- BOITE RÉCAP PANIER -->
<div class="bg-green-100 p-6 rounded-lg mb-8 flex flex-col md:flex-row justify-between items-center gap-4">
    <div>
        <p class="text-lg font-semibold">
            Total produit{{ panier.total_items|pluralize }} : {{ panier.total_items }} 
        </p>
        <p class="text-xl mt-3 font-bold text-green-600">
            Montant Total : {{ panier.total_price }} $
        </p>
    </div>

    <div class="flex gap-4">
        <a href="{% url 'products:list_products' %}"
           class="px-5 py-2 border border-green-500 text-green-600 rounded hover:bg-green-50 transition">
            Continuer les achats
        </a>

        <a href="{% url "commande:checkout" %}"
           class="px-5 py-2 bg-green-500 text-white rounded hover:bg-green-600 transition">
            Passer commande
        </a>
    </div>
</div>

<!-- TABLE PANIER -->
<div class="bg-white rounded-lg shadow overflow-hidden">
    <table class="w-full text-sm md:text-base">
        <thead class="bg-green-100">
            <tr>
                <th class="p-4 text-left">Article</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Prix Total</th>
            </tr>
        </thead>

        <tbody>
        {% for ligne in panier.lignepanier_set.all %}
            <tr class="border-t text-center">
                <td class="p-4 flex items-center gap-4 text-left">
                    <img src="{{ ligne.produit.image.url }}"
                         class="w-16 h-16 object-contain rounded">
                    <span>{{ ligne.produit.nom }}</span>
                </td>

                <td>{{ ligne.produit.prix }} $</td>

                <td>
                    <div class="flex justify-center items-center gap-3">
                        <a href="{% url 'decrease' ligne.id %}"
                           class="px-3 py-1 bg-gray-200 rounded hover:bg-red-500 -translate-y-3">−</a>

                        <span class="font-semibold">{{ ligne.quantite }}</span>

                        <a href="{% url 'increase' ligne.id %}"
                           class="px-3 py-1 bg-gray-200 rounded hover:bg-green-400 -translate-y-3">+</a>
                    </div>
                </td>

                <td class="font-semibold">
                    {{ ligne.total }} $
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="4" class="p-6 text-center text-gray-500">
                    Votre panier est vide 🛒
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}